//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGames.GameEngine {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameEngineResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameEngineResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardGames.GameEngine.GameEngineResources", typeof(GameEngineResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultBackground {
            get {
                object obj = ResourceManager.GetObject("DefaultBackground", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckAceBlackClubs {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckAceBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckAceBlackSpades {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckAceBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckAceRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckAceRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckAceRedHearts {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckAceRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckBack {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckBack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckEightBlackClubs {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckEightBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckEightBlackSpades {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckEightBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckEightRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckEightRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckEightRedHearts {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckEightRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckFiveBlackClubs {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckFiveBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckFiveBlackSpades {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckFiveBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckFiveRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckFiveRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckFiveRedHearts {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckFiveRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckFourBlackClubs {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckFourBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckFourBlackSpades {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckFourBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckFourRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckFourRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckFourRedHearts {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckFourRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckJackBlackClubs {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckJackBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckJackBlackSpades {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckJackBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckJackRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckJackRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckJackRedHearts {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckJackRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckJokerBlackNone {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckJokerBlackNone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckJokerRedNone {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckJokerRedNone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckKingBlackClubs {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckKingBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckKingBlackSpades {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckKingBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckKingRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckKingRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckKingRedHearts {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckKingRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckNineBlackClubs {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckNineBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckNineBlackSpades {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckNineBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckNineRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckNineRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckNineRedHearts {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckNineRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckQueenBlackClubs {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckQueenBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckQueenBlackSpades {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckQueenBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckQueenRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckQueenRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckQueenRedHearts {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckQueenRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckSevenBlackClubs {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckSevenBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckSevenBlackSpades {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckSevenBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckSevenRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckSevenRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckSevenRedHearts {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckSevenRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckSixBlackClubs {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckSixBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckSixBlackSpades {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckSixBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckSixRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckSixRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckSixRedHearts {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckSixRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckTenBlackClubs {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckTenBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckTenBlackSpades {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckTenBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckTenRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckTenRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckTenRedHearts {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckTenRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckThreeBlackClubs {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckThreeBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckThreeBlackSpades {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckThreeBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckThreeRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckThreeRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckThreeRedHearts {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckThreeRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckTwoBlackClubs {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckTwoBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckTwoBlackSpades {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckTwoBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckTwoRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckTwoRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultDeckTwoRedHearts {
            get {
                object obj = ResourceManager.GetObject("DefaultDeckTwoRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] DefaultIcon {
            get {
                object obj = ResourceManager.GetObject("DefaultIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckAceBlackClubs {
            get {
                object obj = ResourceManager.GetObject("SecondDeckAceBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckAceBlackSpades {
            get {
                object obj = ResourceManager.GetObject("SecondDeckAceBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckAceRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("SecondDeckAceRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckAceRedHearts {
            get {
                object obj = ResourceManager.GetObject("SecondDeckAceRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckBack {
            get {
                object obj = ResourceManager.GetObject("SecondDeckBack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckEightBlackClubs {
            get {
                object obj = ResourceManager.GetObject("SecondDeckEightBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckEightBlackSpades {
            get {
                object obj = ResourceManager.GetObject("SecondDeckEightBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckEightRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("SecondDeckEightRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckEightRedHearts {
            get {
                object obj = ResourceManager.GetObject("SecondDeckEightRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckFiveBlackClubs {
            get {
                object obj = ResourceManager.GetObject("SecondDeckFiveBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckFiveBlackSpades {
            get {
                object obj = ResourceManager.GetObject("SecondDeckFiveBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckFiveRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("SecondDeckFiveRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckFiveRedHearts {
            get {
                object obj = ResourceManager.GetObject("SecondDeckFiveRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckFourBlackClubs {
            get {
                object obj = ResourceManager.GetObject("SecondDeckFourBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckFourBlackSpades {
            get {
                object obj = ResourceManager.GetObject("SecondDeckFourBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckFourRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("SecondDeckFourRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckFourRedHearts {
            get {
                object obj = ResourceManager.GetObject("SecondDeckFourRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckJackBlackClubs {
            get {
                object obj = ResourceManager.GetObject("SecondDeckJackBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckJackBlackSpades {
            get {
                object obj = ResourceManager.GetObject("SecondDeckJackBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckJackRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("SecondDeckJackRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckJackRedHearts {
            get {
                object obj = ResourceManager.GetObject("SecondDeckJackRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckJokerBlackNone {
            get {
                object obj = ResourceManager.GetObject("SecondDeckJokerBlackNone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckJokerRedNone {
            get {
                object obj = ResourceManager.GetObject("SecondDeckJokerRedNone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckKingBlackClubs {
            get {
                object obj = ResourceManager.GetObject("SecondDeckKingBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckKingBlackSpades {
            get {
                object obj = ResourceManager.GetObject("SecondDeckKingBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckKingRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("SecondDeckKingRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckKingRedHearts {
            get {
                object obj = ResourceManager.GetObject("SecondDeckKingRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckNineBlackClubs {
            get {
                object obj = ResourceManager.GetObject("SecondDeckNineBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckNineBlackSpades {
            get {
                object obj = ResourceManager.GetObject("SecondDeckNineBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckNineRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("SecondDeckNineRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckNineRedHearts {
            get {
                object obj = ResourceManager.GetObject("SecondDeckNineRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckQueenBlackClubs {
            get {
                object obj = ResourceManager.GetObject("SecondDeckQueenBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckQueenBlackSpades {
            get {
                object obj = ResourceManager.GetObject("SecondDeckQueenBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckQueenRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("SecondDeckQueenRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckQueenRedHearts {
            get {
                object obj = ResourceManager.GetObject("SecondDeckQueenRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckSevenBlackClubs {
            get {
                object obj = ResourceManager.GetObject("SecondDeckSevenBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckSevenBlackSpades {
            get {
                object obj = ResourceManager.GetObject("SecondDeckSevenBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckSevenRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("SecondDeckSevenRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckSevenRedHearts {
            get {
                object obj = ResourceManager.GetObject("SecondDeckSevenRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckSixBlackClubs {
            get {
                object obj = ResourceManager.GetObject("SecondDeckSixBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckSixBlackSpades {
            get {
                object obj = ResourceManager.GetObject("SecondDeckSixBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckSixRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("SecondDeckSixRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckSixRedHearts {
            get {
                object obj = ResourceManager.GetObject("SecondDeckSixRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckTenBlackClubs {
            get {
                object obj = ResourceManager.GetObject("SecondDeckTenBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckTenBlackSpades {
            get {
                object obj = ResourceManager.GetObject("SecondDeckTenBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckTenRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("SecondDeckTenRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckTenRedHearts {
            get {
                object obj = ResourceManager.GetObject("SecondDeckTenRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckThreeBlackClubs {
            get {
                object obj = ResourceManager.GetObject("SecondDeckThreeBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckThreeBlackSpades {
            get {
                object obj = ResourceManager.GetObject("SecondDeckThreeBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckThreeRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("SecondDeckThreeRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckThreeRedHearts {
            get {
                object obj = ResourceManager.GetObject("SecondDeckThreeRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckTwoBlackClubs {
            get {
                object obj = ResourceManager.GetObject("SecondDeckTwoBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckTwoBlackSpades {
            get {
                object obj = ResourceManager.GetObject("SecondDeckTwoBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckTwoRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("SecondDeckTwoRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] SecondDeckTwoRedHearts {
            get {
                object obj = ResourceManager.GetObject("SecondDeckTwoRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckAceBlackClubs {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckAceBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckAceBlackSpades {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckAceBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckAceRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckAceRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckAceRedHearts {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckAceRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckBack {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckBack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckEightBlackClubs {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckEightBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckEightBlackSpades {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckEightBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckEightRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckEightRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckEightRedHearts {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckEightRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckFiveBlackClubs {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckFiveBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckFiveBlackSpades {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckFiveBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckFiveRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckFiveRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckFiveRedHearts {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckFiveRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckFourBlackClubs {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckFourBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckFourBlackSpades {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckFourBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckFourRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckFourRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckFourRedHearts {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckFourRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckJackBlackClubs {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckJackBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckJackBlackSpades {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckJackBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckJackRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckJackRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckJackRedHearts {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckJackRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckJokerBlackNone {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckJokerBlackNone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckJokerRedNone {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckJokerRedNone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckKingBlackClubs {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckKingBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckKingBlackSpades {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckKingBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckKingRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckKingRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckKingRedHearts {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckKingRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckNineBlackClubs {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckNineBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckNineBlackSpades {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckNineBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckNineRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckNineRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckNineRedHearts {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckNineRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckQueenBlackClubs {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckQueenBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckQueenBlackSpades {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckQueenBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckQueenRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckQueenRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckQueenRedHearts {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckQueenRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckSevenBlackClubs {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckSevenBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckSevenBlackSpades {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckSevenBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckSevenRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckSevenRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckSevenRedHearts {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckSevenRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckSixBlackClubs {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckSixBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckSixBlackSpades {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckSixBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckSixRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckSixRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckSixRedHearts {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckSixRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckTenBlackClubs {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckTenBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckTenBlackSpades {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckTenBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckTenRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckTenRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckTenRedHearts {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckTenRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckThreeBlackClubs {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckThreeBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckThreeBlackSpades {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckThreeBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckThreeRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckThreeRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckThreeRedHearts {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckThreeRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckTwoBlackClubs {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckTwoBlackClubs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckTwoBlackSpades {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckTwoBlackSpades", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckTwoRedDiamonds {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckTwoRedDiamonds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] ThirdDeckTwoRedHearts {
            get {
                object obj = ResourceManager.GetObject("ThirdDeckTwoRedHearts", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
